version: '3.4'

networks:
    justa.job.backend.app:
        driver: bridge

services: 
    justa.job.backend.api:
        image: justa.job.backend
        container_name: justa.job.backend.api
        depends_on: 
            - "db"
        build: 
            context: ./src/Justa.Job.Backend.Api
            dockerfile: Dockerfile
        ports: ["5000:80"]
        environment: 
            DB_CONNECTION_STRING: "host=db;port=5432;database=ApplicationDbContext;username=jst;password=jst"
        networks: 
            - justa.job.backend.app

    db:
        image: postgres:latest
        container_name: justa.job.backend.api.db
        ports: ["5432:5432"]
        restart: always
        volumes: 
            - db_volume:/var/lib/postgresql/data
            - ./src/Justa.Job.Backend.Api/seed.sql:/docker-entrypoint-initdb.d/seed.sql
        environment: 
            POSTGRES_USER: "jst"
            POSTGRES_PASSWORD: "jst"
            POSTGRES_DB: "ApplicationDbContext"
        networks:
            - justa.job.backend.app

volumes: 
    db_volume: